### PR TITLE
Escape key correctly closes alert/confirm/dialog

### LINKED ISSUE #106: 'Esc' should close confirm dialog
### Expected behavior
When I open a confirm dialog and hit `Escape`, this should be equivalent to hitting `cancel`

### Actual behavior
Hitting `Escape` doesn't do anything in a confirm dialog

### Steps to reproduce the behavior
Simpy open an `alertify.confirm` and hit `Esc`

### Version of Alertify in use
1.0.11

### PR DESCRIPTION
**Pull request by ram535ii**
Fixes #106, For details/discussion see #111

### CODE REVIEW

**Comment by ram535ii** [comment]
@bradberger are you planning to release a new version off the back of this?

**Comment by ChunkRadius** [comment]
@ram535ii Yes it will be 1.0.12

**Comment by ram535ii** [comment]
@bradberger Cool, anyway to release it on Bower as well?

**Comment by masoomulhaqs** [comment]
@bradberger I have installed alertify@1.0.12 using npm. However, the dialog is not closing on press of 'esc' or on click outside the dialog. Any update on this?

**Pull request merged**
